export const PERMISSIONS = [
  'NOTES_VIEW',
  'NOTE_CONTENT_VIEW',
  'NOTE_EDIT',
  'NOTE_HISTORY_VIEW',
  'REVIEW_EVENTS_VIEW',
  'REVIEW_START',
  'REVIEW_RETURN',
  'REVIEW_APPROVE',
  'REVIEW_REJECT',
  'NOTE_RESUBMIT',
  'NOTE_REGENERATE',
  'NOTE_AMEND',
  'NOTE_ASSIGN_REVIEWER',
  'NOTE_BULK_ASSIGN_REVIEWER',
  'NOTE_BULK_REGENERATE',
  'ADMIN_SIMULATION_CONTROL',
] as const

export type Permission = (typeof PERMISSIONS)[number]
